import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import SideBar from './components/SideBar'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { ApiProvider } from './api/common/ApiProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'KnowledgeBase',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ApiProvider>
      <html lang="en">
        <body className={inter.className}>
            <div className='p-24'>
              {children}
            </div>
        </body>
      </html>
    </ApiProvider>
  )
}
